version: '3.8'

services:
  mysql-user-db:
    image: mysql
    container_name: mysql-user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql

  user-service:
    image: ${SERVICE_IMAGE}
    depends_on:
      - mysql-user-db
    restart: always
    env_file: .env
    ports:
      - "3000:3000"


volumes:
  mysql_user_data: