
export enum PermissionCode {
    USER_GET_ALL = 'USER_GET_ALL',
    USER_GET_DETAIL = 'USER_GET_DETAIL',
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_DELETE = 'USER_DELETE',

    ROLE_GET_ALL = 'ROLE_GET_ALL',
    ROLE_CREATE = 'ROLE_CREATE',
    ROLE_UPDATE = 'ROLE_UPDATE',
    ROLE_DELETE = 'ROLE_DELETE',

    PERMISSION_GET_ALL = 'PERMISSION_GET_ALL',
    PERMISSION_CREATE = 'PERMISSION_CREATE',
    PERMISSION_UPDATE = 'PERMISSION_UPDATE',
    PERMISSION_DELETE = 'PERMISSION_DELETE',

    USER_ASSIGN_ROLE = 'USER_ASSIGN_ROLE',
    USER_REVOKE_ROLE = 'USER_REVOKE_ROLE',

    ROLE_ASSIGN_PERMISSION = 'ROLE_ASSIGN_PERMISSION',
    ROLE_REVOKE_PERMISSION = 'ROLE_REVOKE_PERMISSION',

    AUDIT_LOG_VIEW = 'AUDIT_LOG_VIEW',
    AUDIT_LOG_DOWNLOAD = 'AUDIT_LOG_DOWNLOAD',
}